import { promises as fs } from 'node:fs';
import path from 'node:path';
import {
  runDetectDeps,
  type TAppCoupling,
  type TDetectDepsLibraryReport,
} from './detect-deps.js';

/* ========================================================================== */
/*                          COUPLINGS — REPORT WRITER                         */
/* ========================================================================== */

/**
 * Generates a persistent markdown report listing every app-coupling
 * violation in each library. Reuses the import scanner from
 * `detect-deps`; this command is purely the report-writing surface so
 * the output can be checked into git or fed to a refactor effort.
 *
 * One file per library is written under `<outDir>/<library>.md`. The
 * report is grouped by importing-file, with line anchors and a
 * suggested canonical-alias replacement when one can be derived.
 *
 * Files for libraries with zero couplings are still written, so the
 * directory always reflects the latest scan (no stale leftovers from
 * libraries that have since been cleaned up). When no entries exist,
 * the file just states that.
 */

/* -------------------------------------------------------------------------- */
/* Public API                                                                 */
/* -------------------------------------------------------------------------- */

export type TCouplingsOptions = {
  hostRoot: string;
  /** Project-relative path where libraries live (e.g. `/src/lib`). */
  localLibraryPath: string;
  /** Restrict to a single library. */
  name?: string;
  /** Where to write the markdown reports (absolute or host-relative). */
  outDir: string;
  /** When true, compute reports but write nothing. */
  dryRun: boolean;
};

export type TCouplingsLibrarySummary = {
  name: string;
  /** Total app couplings detected for this library. */
  totalCouplings: number;
  /** How many of those have a mechanical canonical-alias fix. */
  fixableCouplings: number;
  /** Absolute path to the markdown file written (or that would be). */
  reportPath: string;
  /** Whether anything was written (false in dry-run, or when unchanged). */
  written: boolean;
};

export type TCouplingsResult = {
  ok: boolean;
  error?: string;
  outDir: string;
  reports: TCouplingsLibrarySummary[];
};

export async function runCouplings(
  opts: TCouplingsOptions,
): Promise<TCouplingsResult> {
  const { hostRoot, localLibraryPath, name, outDir, dryRun } = opts;

  /* delegate the scan to detect-deps in dry-run mode (never writes) */
  const detect = await runDetectDeps({
    hostRoot,
    localLibraryPath,
    name,
    dryRun: true,
  });

  if (!detect.ok) {
    return {
      ok: false,
      error: detect.error,
      outDir,
      reports: [],
    };
  }

  const absOutDir = path.isAbsolute(outDir)
    ? outDir
    : path.join(hostRoot, outDir);

  if (!dryRun) {
    await fs.mkdir(absOutDir, { recursive: true });
  }

  const reports: TCouplingsLibrarySummary[] = [];
  for (const libReport of detect.reports) {
    if (libReport.error) {
      reports.push({
        name: libReport.name,
        totalCouplings: 0,
        fixableCouplings: 0,
        reportPath: path.join(absOutDir, `${libReport.name}.md`),
        written: false,
      });
      continue;
    }

    const reportPath = path.join(absOutDir, `${libReport.name}.md`);
    const md = renderLibraryMarkdown(libReport, hostRoot);

    let written = false;
    if (!dryRun) {
      written = await writeIfChanged(reportPath, md);
    }

    reports.push({
      name: libReport.name,
      totalCouplings: libReport.appCouplings.length,
      fixableCouplings: libReport.appCouplings.filter((c) => c.suggestedFix)
        .length,
      reportPath,
      written,
    });
  }

  /* index file — single overview pointing at every per-library report */
  if (!dryRun) {
    const indexPath = path.join(absOutDir, 'README.md');
    const indexMd = renderIndexMarkdown(reports, absOutDir, hostRoot);
    await writeIfChanged(indexPath, indexMd);
  }

  return { ok: true, outDir: absOutDir, reports };
}

/* -------------------------------------------------------------------------- */
/* Markdown rendering                                                         */
/* -------------------------------------------------------------------------- */

function renderLibraryMarkdown(
  libReport: TDetectDepsLibraryReport,
  hostRoot: string,
): string {
  const { name, appCouplings, filesScanned } = libReport;
  const lines: string[] = [];

  lines.push(`# \`@${name}\` — app-coupling report`);
  lines.push('');
  lines.push(
    `Generated by \`lib couplings\`. ${filesScanned} file${filesScanned === 1 ? '' : 's'} scanned. ` +
      `${appCouplings.length} coupling${appCouplings.length === 1 ? '' : 's'} found.`,
  );
  lines.push('');

  if (appCouplings.length === 0) {
    lines.push('No app couplings detected. Nothing to fix.');
    lines.push('');
    return lines.join('\n');
  }

  const fixableCount = appCouplings.filter((c) => c.suggestedFix).length;
  const decouplingCount = appCouplings.length - fixableCount;

  lines.push('## Summary');
  lines.push('');
  lines.push(
    `- ${fixableCount} entr${fixableCount === 1 ? 'y' : 'ies'} have a ` +
      `mechanical canonical-alias fix (host alias → library alias).`,
  );
  lines.push(
    `- ${decouplingCount} entr${decouplingCount === 1 ? 'y' : 'ies'} ` +
      `need a real decoupling decision (no library alias matches, or the ` +
      `import escapes the library directory entirely).`,
  );
  lines.push('');

  /* group couplings by file */
  const byFile = new Map<string, TAppCoupling[]>();
  for (const c of appCouplings) {
    let bucket = byFile.get(c.file);
    if (!bucket) {
      bucket = [];
      byFile.set(c.file, bucket);
    }
    bucket.push(c);
  }
  const sortedFiles = [...byFile.keys()].sort();

  lines.push('## By file');
  lines.push('');

  for (const file of sortedFiles) {
    const entries = byFile.get(file)!;
    entries.sort((a, b) => a.line - b.line);

    lines.push(`### \`${file}\``);
    lines.push('');
    for (const e of entries) {
      const reasonLabel =
        e.reason === 'host-alias'
          ? 'host alias'
          : 'relative path escapes library';
      const fix = e.suggestedFix
        ? ` → \`${e.suggestedFix}\` (canonical alias)`
        : ' → **needs decoupling decision**';
      lines.push(
        `- [\`${file}:${e.line}\`](/${file}#L${e.line}) — \`${e.specifier}\` ` +
          `(${reasonLabel})${fix}`,
      );
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push(
    `Re-run \`lib couplings ${name}\` to refresh. Strictly read-only — ` +
      `this file is regenerated each run, not edited by hand.`,
  );
  lines.push('');

  // hostRoot is included for future use (e.g., absolute file links). Suppress
  // unused-var lints by referring to it once.
  void hostRoot;

  return lines.join('\n');
}

function renderIndexMarkdown(
  reports: TCouplingsLibrarySummary[],
  outDir: string,
  hostRoot: string,
): string {
  const lines: string[] = [];
  lines.push('# Library app-coupling reports');
  lines.push('');
  lines.push(
    'Generated by `lib couplings`. Each per-library report lists every ' +
      'import in that library that escapes its boundary — host aliases ' +
      '(`@/...`), tsconfig paths, or relative paths that resolve outside ' +
      'the library directory.',
  );
  lines.push('');
  lines.push('| Library | couplings | fixable (canonical alias) |');
  lines.push('| --- | ---: | ---: |');
  for (const r of [...reports].sort((a, b) =>
    b.totalCouplings - a.totalCouplings || a.name.localeCompare(b.name),
  )) {
    const relPath = path.relative(outDir, r.reportPath);
    lines.push(
      `| [\`@${r.name}\`](./${relPath}) | ${r.totalCouplings} | ${r.fixableCouplings} |`,
    );
  }
  lines.push('');
  lines.push(
    `Reports root: \`${path.relative(hostRoot, outDir).replace(/\\/g, '/')}\``,
  );
  lines.push('');
  return lines.join('\n');
}

/* -------------------------------------------------------------------------- */
/* Write only if content differs (idempotent runs don't bump mtime)           */
/* -------------------------------------------------------------------------- */

async function writeIfChanged(
  filePath: string,
  contents: string,
): Promise<boolean> {
  try {
    const existing = await fs.readFile(filePath, 'utf8');
    if (existing === contents) return false;
  } catch {
    // file doesn't exist — fall through to write
  }
  await fs.writeFile(filePath, contents);
  return true;
}
